<?php

namespace AppBundle\Repository;

/**
 * WebsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRepository extends \Doctrine\ORM\EntityRepository {
	public function getWebsitesCount()
	{
		$count = $this->createQueryBuilder('w')
				->select('count(w.id)')
				->getQuery()
				->getSingleScalarResult();

		return $count;
	}

	public function findRandomWebsite()
	{
		$count = $this->getWebsitesCount();
		$offset = rand(0, $count);

		$website = $this->createQueryBuilder('w')
				->setFirstResult($offset)
				->setMaxResults(1)
				->getQuery()
				->getArrayResult();

		return $website;
	}
}
